global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'web_metrics'
    metrics_path: /metrics
    static_configs:
      - targets: ['metrics-api:8080']

  - job_name: 'blackbox_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://blog.entazis.dev/
          - https://blog.entazis.dev/rss.xml
          - https://blog.entazis.dev/sitemap.xml
          - https://blog.entazis.dev/en/rss.xml
          - https://blog.entazis.dev/robots.txt
          - https://dice.entazis.dev/
          - https://decision-matrix.entazis.dev/
          - https://nvc-helper.entazis.dev/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'nginx'
    metrics_path: /metrics
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: ['node-exporter:9100']
